/**
 *
 *  PortfolioSnapshots.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PortfolioSnapshots.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::investments;

const std::string PortfolioSnapshots::Cols::_id = "\"id\"";
const std::string PortfolioSnapshots::Cols::_user_id = "\"user_id\"";
const std::string PortfolioSnapshots::Cols::_total_value = "\"total_value\"";
const std::string PortfolioSnapshots::Cols::_snapshot_date = "\"snapshot_date\"";
const std::string PortfolioSnapshots::primaryKeyName = "id";
const bool PortfolioSnapshots::hasPrimaryKey = true;
const std::string PortfolioSnapshots::tableName = "\"portfolio_snapshots\"";

const std::vector<typename PortfolioSnapshots::MetaData> PortfolioSnapshots::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"user_id","int64_t","bigint",8,0,0,1},
{"total_value","std::string","numeric",0,0,0,1},
{"snapshot_date","::trantor::Date","date",0,0,0,1}
};
const std::string &PortfolioSnapshots::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PortfolioSnapshots::PortfolioSnapshots(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["total_value"].isNull())
        {
            totalValue_=std::make_shared<std::string>(r["total_value"].as<std::string>());
        }
        if(!r["snapshot_date"].isNull())
        {
            auto daysStr = r["snapshot_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            snapshotDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            totalValue_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            snapshotDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }

}

PortfolioSnapshots::PortfolioSnapshots(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            totalValue_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            snapshotDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

PortfolioSnapshots::PortfolioSnapshots(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("total_value"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["total_value"].isNull())
        {
            totalValue_=std::make_shared<std::string>(pJson["total_value"].asString());
        }
    }
    if(pJson.isMember("snapshot_date"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["snapshot_date"].isNull())
        {
            auto daysStr = pJson["snapshot_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            snapshotDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void PortfolioSnapshots::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            totalValue_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            snapshotDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void PortfolioSnapshots::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("total_value"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["total_value"].isNull())
        {
            totalValue_=std::make_shared<std::string>(pJson["total_value"].asString());
        }
    }
    if(pJson.isMember("snapshot_date"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["snapshot_date"].isNull())
        {
            auto daysStr = pJson["snapshot_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            snapshotDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

const int64_t &PortfolioSnapshots::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PortfolioSnapshots::getId() const noexcept
{
    return id_;
}
void PortfolioSnapshots::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename PortfolioSnapshots::PrimaryKeyType & PortfolioSnapshots::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &PortfolioSnapshots::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PortfolioSnapshots::getUserId() const noexcept
{
    return userId_;
}
void PortfolioSnapshots::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[1] = true;
}

const std::string &PortfolioSnapshots::getValueOfTotalValue() const noexcept
{
    static const std::string defaultValue = std::string();
    if(totalValue_)
        return *totalValue_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PortfolioSnapshots::getTotalValue() const noexcept
{
    return totalValue_;
}
void PortfolioSnapshots::setTotalValue(const std::string &pTotalValue) noexcept
{
    totalValue_ = std::make_shared<std::string>(pTotalValue);
    dirtyFlag_[2] = true;
}
void PortfolioSnapshots::setTotalValue(std::string &&pTotalValue) noexcept
{
    totalValue_ = std::make_shared<std::string>(std::move(pTotalValue));
    dirtyFlag_[2] = true;
}

const ::trantor::Date &PortfolioSnapshots::getValueOfSnapshotDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(snapshotDate_)
        return *snapshotDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PortfolioSnapshots::getSnapshotDate() const noexcept
{
    return snapshotDate_;
}
void PortfolioSnapshots::setSnapshotDate(const ::trantor::Date &pSnapshotDate) noexcept
{
    snapshotDate_ = std::make_shared<::trantor::Date>(pSnapshotDate.roundDay());
    dirtyFlag_[3] = true;
}

void PortfolioSnapshots::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PortfolioSnapshots::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "total_value",
        "snapshot_date"
    };
    return inCols;
}

void PortfolioSnapshots::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTotalValue())
        {
            binder << getValueOfTotalValue();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSnapshotDate())
        {
            binder << getValueOfSnapshotDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PortfolioSnapshots::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void PortfolioSnapshots::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTotalValue())
        {
            binder << getValueOfTotalValue();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSnapshotDate())
        {
            binder << getValueOfSnapshotDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PortfolioSnapshots::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getTotalValue())
    {
        ret["total_value"]=getValueOfTotalValue();
    }
    else
    {
        ret["total_value"]=Json::Value();
    }
    if(getSnapshotDate())
    {
        ret["snapshot_date"]=getSnapshotDate()->toDbStringLocal();
    }
    else
    {
        ret["snapshot_date"]=Json::Value();
    }
    return ret;
}

std::string PortfolioSnapshots::toString() const
{
    return toJson().toStyledString();
}

Json::Value PortfolioSnapshots::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTotalValue())
            {
                ret[pMasqueradingVector[2]]=getValueOfTotalValue();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSnapshotDate())
            {
                ret[pMasqueradingVector[3]]=getSnapshotDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getTotalValue())
    {
        ret["total_value"]=getValueOfTotalValue();
    }
    else
    {
        ret["total_value"]=Json::Value();
    }
    if(getSnapshotDate())
    {
        ret["snapshot_date"]=getSnapshotDate()->toDbStringLocal();
    }
    else
    {
        ret["snapshot_date"]=Json::Value();
    }
    return ret;
}

bool PortfolioSnapshots::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("total_value"))
    {
        if(!validJsonOfField(2, "total_value", pJson["total_value"], err, true))
            return false;
    }
    else
    {
        err="The total_value column cannot be null";
        return false;
    }
    if(pJson.isMember("snapshot_date"))
    {
        if(!validJsonOfField(3, "snapshot_date", pJson["snapshot_date"], err, true))
            return false;
    }
    else
    {
        err="The snapshot_date column cannot be null";
        return false;
    }
    return true;
}
bool PortfolioSnapshots::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PortfolioSnapshots::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(1, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("total_value"))
    {
        if(!validJsonOfField(2, "total_value", pJson["total_value"], err, false))
            return false;
    }
    if(pJson.isMember("snapshot_date"))
    {
        if(!validJsonOfField(3, "snapshot_date", pJson["snapshot_date"], err, false))
            return false;
    }
    return true;
}
bool PortfolioSnapshots::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PortfolioSnapshots::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
